use_frameworks!

platform :ios, '9.0'

target 'TestPodLib_Example' do
  pod 'TestPodLib', :path => '../'

  target 'TestPodLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
